### ISSUE TITLE
Paladin issues.

### ISSUE THREAD

**Issue by harukaze3** [BelsethUwU/BelsethUwU.github.io#1]
![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/76977299/4ceb1087-58ae-4aef-aff7-cad6e5b77f44)

- missing icon.

![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/76977299/c409a509-8ffc-4954-ab26-6d21e54d9b26)

- Crusader Strike is in place of Imp BoM.

**Comment by harukaze3** [comment]
![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/76977299/626d6cf4-9d4d-48c9-8945-9aeceb6e70e8)

> Two-Handed Weapon Spec doesn't transform into Zeal.

**Comment by IllustreDot** [comment]
https://github.com/BelsethUwU/BelsethUwU.github.io/issues/2
