### ISSUE TITLE
Retribution Paladin tree

### ISSUE THREAD

**Issue by Kolopit** [BelsethUwU/BelsethUwU.github.io#2]
**Issues on Rows:**

**Row 2**

- Crusader strike missing
- Improved BoM should not be here
![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/133521718/07ac0791-c3b9-4114-95ce-720bb1056a65)

**Row 5**

- Two-hand specialization has different tooltip ingame
![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/133521718/b188ad06-80ce-457b-944a-d23b645ab5ab)

**Row 6**

- Divine Purpose has different tooltip ingame
![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/133521718/b57ee000-1812-492e-9348-99e269f8def4)

**Row 9**

- Place improved BoM here
![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/133521718/a0e0d7e1-c463-4be3-9682-502575e6e3e7)

**Comment by IllustreDot** [comment]
👌 Thank's for the report
