### ISSUE TITLE
Frost DK issues

### ISSUE THREAD

**Issue by Kolopit** [BelsethUwU/BelsethUwU.github.io#3]
**Issues on rows:**

**Row 8**

- Might of the Frozen Wastes has different description ingame 
![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/133521718/53b80add-0e78-4482-b0aa-3212b2eaaff3)

**Row 10**

- Tundra stalker does not give the original 3% per TE
![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/133521718/6289325e-873f-4fd1-b2ce-1e1d930c0e7c)

**Comment by IllustreDot** [comment]
Done 👌
