### ISSUE TITLE
Retribution Paladin tree bug

### ISSUE THREAD

**Issue by zobimaru91** [BelsethUwU/BelsethUwU.github.io#4]
you cant invest more than 1 point in reckoning

**Comment by IllustreDot** [comment]
You can but you need to unselect Seraphin if you want to add or remove point from it. This is currently the only fix I found to the issue of having talent that requires less than max point from their previous required talent. Also it's Protection Paladin not Retribution

**Comment by zobimaru91** [comment]
im sorry brain.exe not working and said retribution
but yeah ive noticed it works if you add and then remove. 
just contributing to the "community"

also its missing the keystone talent for protection (the one bellow touched by the light) which increases your resistances from % of your strength

**Comment by IllustreDot** [comment]
Screen me the IG version please

**Comment by IllustreDot** [comment]
Done, icon is missing and will be added later.
