### ISSUE TITLE
Hunter MM tree problem

### ISSUE THREAD

**Issue by yoyosan** [BelsethUwU/BelsethUwU.github.io#5]
The online talent builder is bugged for the Hunter MM tree.

See images, left is online builder, right is in-game

What's wrong is that `Poisonous Shots` shouldn't be tied to  `Improved Arcane Shot` and should be under `Go for the Throat`

Online builder

![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/32405/e7576c82-b310-44b6-90fd-5da0446373b1)

In-game builder

![image](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/32405/52182e9a-fe2a-4153-b533-149aa9ceef8e)

**Comment by yoyosan** [comment]
While debugging it, I realized that they're only reversed due to the way the talents are added. You just need to add points into `Improved Arcane Shot` first to unlock `Poisonous Shots`. Looking for a way to reverse and still make it usable like in-game.

**Comment by IllustreDot** [comment]
Fixed by https://github.com/yoyosan
