### ISSUE TITLE
Publish the site to github pages

### ISSUE THREAD

**Issue by Tegas** [BelsethUwU/BelsethUwU.github.io#6]
It looks like the app is basically static content. You can have github copy the files to github pages and then let users go directly to that site. You can even use the github custom actions to automatically build whenever you push a commit. 

See: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by IllustreDot** [comment]
Already the case, Hard reload if you don't see the update, Ctrl R/Ctrl F5
