### ISSUE TITLE
Resto Shaman Talents

### ISSUE THREAD

**Issue by Jallarial** [BelsethUwU/BelsethUwU.github.io#8]
The Shaman talent 'Healing Grace' in the Resto tree does not display the correct tooltip for Duskhaven.

**Comment by IllustreDot** [comment]
Link a screen or write the one from IG.

**Comment by Jallarial** [comment]
Sure thing.
![Calc Shot](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/133578511/92041a5d-59fa-45dd-952b-fc369a54e910)

![Game Shot](https://github.com/BelsethUwU/BelsethUwU.github.io/assets/133578511/2eccf8ce-25ed-4330-a040-d054615081b1)

**Comment by IllustreDot** [comment]
Thank's and fixed !
